apiVersion: v1
kind: Service
metadata:
  name: k8-blast-radius-service
spec:
  selector:
    app: flask-blast-radius
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer